import {createRequire} from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.ARES_QA_NODE_MODULES+'/playwright');
const root=path.resolve('.');
const html=fs.readFileSync(path.join(root,'aresfit-dialer-sandde-v2.html'),'utf8');
let calls=0,failNext=false;
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:390,height:844}});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/*',async route=>{
  const u=new URL(route.request().url());
  if(u.origin==='https://script.googleusercontent.com')return route.fulfill({contentType:'text/html',body:`<iframe id="app" style="width:100%;height:100vh;border:0" src="https://michaelini0309.github.io/aresfit-dialer-live-rebuild/aresfit-dialer-sandde-v2.html#aresfit-bridge=qa-nonce"></iframe><script>window.addEventListener('message',e=>{let m=e.data;if(m.type==='ARES_LIVE_READY')e.source.postMessage({type:'ARES_LIVE_INIT',nonce:'qa-nonce'},e.origin);if(m.type==='ARES_LIVE_REQUEST'){window.parent.__request(m).then(r=>e.source.postMessage(r,e.origin))}})</script>`});
  if(u.pathname.endsWith('aresfit-dialer-sandde-v2.html'))return route.fulfill({contentType:'text/html',body:html});
  const file=path.join(root,u.pathname.replace('/aresfit-dialer-live-rebuild/',''));
  if(file.startsWith(root)&&fs.existsSync(file))return route.fulfill({body:fs.readFileSync(file),contentType:file.endsWith('.png')?'image/png':'text/javascript'});
  return route.abort();
 });
 await page.exposeFunction('__request',async m=>{
  if(m.method==='logActivityForSignedInUser')return {type:'ARES_LIVE_RESPONSE',nonce:'qa-nonce',request_id:m.request_id,result:{ok:true,event_id:m.args[0].event_id,global_site_id:m.args[0].global_site_id}};
  calls++;await new Promise(r=>setTimeout(r,400));
  if(failNext){failNext=false;return {type:'ARES_LIVE_RESPONSE',nonce:'qa-nonce',request_id:m.request_id,error:'Deliberate QA connection error'}};
  const start=calls===1?0:50;
  return {type:'ARES_LIVE_RESPONSE',nonce:'qa-nonce',request_id:m.request_id,result:{ok:true,user:{name:'Michael',email:'michael@aresfit.co.uk',rep_id:'REP-MICHAEL'},leads:Array.from({length:50},(_,i)=>({global_site_id:'AFS-'+String(start+i+1).padStart(6,'0'),business_name:'QA Fitness '+(start+i+1),phone:'01234567890',website:'https://example.org',activity_status:'Uncalled',queue_lane:'COLD',latest_notes:'',contact_history:'',queue_reason:'Cold assigned lead'})),remaining:100,next_cursor:'00000000-0000-0000-0000-000000000001',queue_cursor:'00000000-0000-0000-0000-000000000001'}};
 });
 await page.goto('https://script.googleusercontent.com/qa-host');
 const frame=page.frames().find(f=>f.url().includes('aresfit-dialer-sandde-v2.html'));
 await frame.waitForSelector('#setup-modal',{state:'visible'});
 assert.equal(calls,0,'fresh open must not load registry');
 assert.equal(await frame.locator('#live-loading').isVisible(),false);
 assert.equal(await frame.locator('#setup-modal').getByText('Ioan',{exact:true}).count(),0);
 assert.equal(await frame.locator('#setup-modal').getByText('Krzysztof',{exact:true}).count(),1);
 await frame.locator('#setup-name').fill('Michael');await frame.locator('#setup-email').fill('michael@aresfit.co.uk');
 await frame.locator('#setup-modal').getByRole('button',{name:'Save',exact:true}).click();
 assert.equal(calls,0,'saving sender must not load registry');
 await frame.locator('#live-refresh-btn').click();
 await frame.waitForSelector('#live-loading',{state:'visible'});
 await frame.waitForSelector('#main-app',{state:'visible'});
 assert.equal(await frame.locator('#live-loading').isVisible(),false);
 assert.equal(await frame.evaluate(()=>leads.length),50);
 const selected=await frame.evaluate(()=>getLeadId(filtered[idx]));
 await frame.locator('#live-next-btn').click();
 assert.equal(await frame.locator('#live-loading').isVisible(),false,'next batch must not cover app');
 await frame.waitForFunction(()=>leads.length===100);
 assert.equal(await frame.evaluate(()=>getLeadId(filtered[idx])),selected);
 await frame.evaluate(()=>appendEventRow(buildEventRow(filtered[idx],{channel:'call',outcome:'reached',next_action:'CALL',next_action_date:'2026-09-30 10:00',proof_source:'QA mock only',notes:'Original QA customer note'})));
 await frame.waitForFunction(()=>eventLog.length>0&&eventLog.at(-1)._sync_status==='synced');
 assert.equal(await frame.evaluate(()=>eventLog.at(-1).lead_id),selected);
 assert.equal(await frame.evaluate(()=>eventLog.at(-1).notes),'Original QA customer note');
 assert.equal(await frame.evaluate(()=>loadLiveOutbox().length),0);
 await frame.locator('#live-next-btn').click();await frame.waitForTimeout(600);
 assert.equal(await frame.evaluate(()=>leads.length),100,'duplicate page must not duplicate leads');
 failNext=true;await frame.locator('#live-next-btn').click();await frame.waitForTimeout(600);
 assert.equal(await frame.locator('#live-loading').isVisible(),false);
 assert.equal(await frame.locator('#live-next-btn').isDisabled(),false);
 await page.reload();const again=page.frames().find(f=>f.url().includes('aresfit-dialer-sandde-v2.html'));
 await again.waitForSelector('#setup-modal',{state:'visible'});
 assert.equal(await again.locator('#live-loading').isVisible(),false,'reopen must start with sender');
 assert.deepEqual(errors,[]);
 console.log('PASS: mobile sender first, Save does not load, Connect loader, next 50 without overlay, stable selected ID, dedupe, failure recovery, reopen sender, no page errors');
 await context.close();
}finally{await browser.close()}
